module.exports = {
  config: {
    fontSize: 14,
    fontFamily: 'Cascadia Code, Fira Code, Consolas, monospace',
    cursorColor: '#00ffd5',
    cursorAccentColor: '#000000',
    foregroundColor: '#d7f9ff',
    backgroundColor: '#07111f',
    selectionColor: 'rgba(0, 255, 213, 0.25)',
    borderColor: '#0f2740',
    css: '',
    shell: '',
    shellArgs: [],
    env: {},
    bell: 'SOUND',
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    showHamburgerMenu: true,
    showWindowControls: true,
    padding: '12px 14px',
    colors: {
      black: '#08121f',
      red: '#ff5f56',
      green: '#5af78e',
      yellow: '#f3f99d',
      blue: '#57c7ff',
      magenta: '#ff6ac1',
      cyan: '#9aedfe',
      white: '#f1f1f0',
      lightBlack: '#4d4d4d',
      lightRed: '#ff7b72',
      lightGreen: '#72f1b8',
      lightYellow: '#f9f871',
      lightBlue: '#8be9fd',
      lightMagenta: '#ff92d0',
      lightCyan: '#a4ffff',
      lightWhite: '#ffffff'
    }
  },
  plugins: [],
  localPlugins: [],
  keymaps: {}
};
